require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CasafuncionariosController do

  # This should return the minimal set of attributes required to create a valid
  # Casafuncionario. As you add validations to Casafuncionario, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "casa" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CasafuncionariosController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all casafuncionarios as @casafuncionarios" do
      casafuncionario = Casafuncionario.create! valid_attributes
      get :index, {}, valid_session
      assigns(:casafuncionarios).should eq([casafuncionario])
    end
  end

  describe "GET show" do
    it "assigns the requested casafuncionario as @casafuncionario" do
      casafuncionario = Casafuncionario.create! valid_attributes
      get :show, {:id => casafuncionario.to_param}, valid_session
      assigns(:casafuncionario).should eq(casafuncionario)
    end
  end

  describe "GET new" do
    it "assigns a new casafuncionario as @casafuncionario" do
      get :new, {}, valid_session
      assigns(:casafuncionario).should be_a_new(Casafuncionario)
    end
  end

  describe "GET edit" do
    it "assigns the requested casafuncionario as @casafuncionario" do
      casafuncionario = Casafuncionario.create! valid_attributes
      get :edit, {:id => casafuncionario.to_param}, valid_session
      assigns(:casafuncionario).should eq(casafuncionario)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Casafuncionario" do
        expect {
          post :create, {:casafuncionario => valid_attributes}, valid_session
        }.to change(Casafuncionario, :count).by(1)
      end

      it "assigns a newly created casafuncionario as @casafuncionario" do
        post :create, {:casafuncionario => valid_attributes}, valid_session
        assigns(:casafuncionario).should be_a(Casafuncionario)
        assigns(:casafuncionario).should be_persisted
      end

      it "redirects to the created casafuncionario" do
        post :create, {:casafuncionario => valid_attributes}, valid_session
        response.should redirect_to(Casafuncionario.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved casafuncionario as @casafuncionario" do
        # Trigger the behavior that occurs when invalid params are submitted
        Casafuncionario.any_instance.stub(:save).and_return(false)
        post :create, {:casafuncionario => { "casa" => "invalid value" }}, valid_session
        assigns(:casafuncionario).should be_a_new(Casafuncionario)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Casafuncionario.any_instance.stub(:save).and_return(false)
        post :create, {:casafuncionario => { "casa" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested casafuncionario" do
        casafuncionario = Casafuncionario.create! valid_attributes
        # Assuming there are no other casafuncionarios in the database, this
        # specifies that the Casafuncionario created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Casafuncionario.any_instance.should_receive(:update).with({ "casa" => "" })
        put :update, {:id => casafuncionario.to_param, :casafuncionario => { "casa" => "" }}, valid_session
      end

      it "assigns the requested casafuncionario as @casafuncionario" do
        casafuncionario = Casafuncionario.create! valid_attributes
        put :update, {:id => casafuncionario.to_param, :casafuncionario => valid_attributes}, valid_session
        assigns(:casafuncionario).should eq(casafuncionario)
      end

      it "redirects to the casafuncionario" do
        casafuncionario = Casafuncionario.create! valid_attributes
        put :update, {:id => casafuncionario.to_param, :casafuncionario => valid_attributes}, valid_session
        response.should redirect_to(casafuncionario)
      end
    end

    describe "with invalid params" do
      it "assigns the casafuncionario as @casafuncionario" do
        casafuncionario = Casafuncionario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Casafuncionario.any_instance.stub(:save).and_return(false)
        put :update, {:id => casafuncionario.to_param, :casafuncionario => { "casa" => "invalid value" }}, valid_session
        assigns(:casafuncionario).should eq(casafuncionario)
      end

      it "re-renders the 'edit' template" do
        casafuncionario = Casafuncionario.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Casafuncionario.any_instance.stub(:save).and_return(false)
        put :update, {:id => casafuncionario.to_param, :casafuncionario => { "casa" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested casafuncionario" do
      casafuncionario = Casafuncionario.create! valid_attributes
      expect {
        delete :destroy, {:id => casafuncionario.to_param}, valid_session
      }.to change(Casafuncionario, :count).by(-1)
    end

    it "redirects to the casafuncionarios list" do
      casafuncionario = Casafuncionario.create! valid_attributes
      delete :destroy, {:id => casafuncionario.to_param}, valid_session
      response.should redirect_to(casafuncionarios_url)
    end
  end

end
