require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CasasController do

  # This should return the minimal set of attributes required to create a valid
  # Casa. As you add validations to Casa, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "rua" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CasasController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all casas as @casas" do
      casa = Casa.create! valid_attributes
      get :index, {}, valid_session
      assigns(:casas).should eq([casa])
    end
  end

  describe "GET show" do
    it "assigns the requested casa as @casa" do
      casa = Casa.create! valid_attributes
      get :show, {:id => casa.to_param}, valid_session
      assigns(:casa).should eq(casa)
    end
  end

  describe "GET new" do
    it "assigns a new casa as @casa" do
      get :new, {}, valid_session
      assigns(:casa).should be_a_new(Casa)
    end
  end

  describe "GET edit" do
    it "assigns the requested casa as @casa" do
      casa = Casa.create! valid_attributes
      get :edit, {:id => casa.to_param}, valid_session
      assigns(:casa).should eq(casa)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Casa" do
        expect {
          post :create, {:casa => valid_attributes}, valid_session
        }.to change(Casa, :count).by(1)
      end

      it "assigns a newly created casa as @casa" do
        post :create, {:casa => valid_attributes}, valid_session
        assigns(:casa).should be_a(Casa)
        assigns(:casa).should be_persisted
      end

      it "redirects to the created casa" do
        post :create, {:casa => valid_attributes}, valid_session
        response.should redirect_to(Casa.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved casa as @casa" do
        # Trigger the behavior that occurs when invalid params are submitted
        Casa.any_instance.stub(:save).and_return(false)
        post :create, {:casa => { "rua" => "invalid value" }}, valid_session
        assigns(:casa).should be_a_new(Casa)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Casa.any_instance.stub(:save).and_return(false)
        post :create, {:casa => { "rua" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested casa" do
        casa = Casa.create! valid_attributes
        # Assuming there are no other casas in the database, this
        # specifies that the Casa created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Casa.any_instance.should_receive(:update).with({ "rua" => "MyString" })
        put :update, {:id => casa.to_param, :casa => { "rua" => "MyString" }}, valid_session
      end

      it "assigns the requested casa as @casa" do
        casa = Casa.create! valid_attributes
        put :update, {:id => casa.to_param, :casa => valid_attributes}, valid_session
        assigns(:casa).should eq(casa)
      end

      it "redirects to the casa" do
        casa = Casa.create! valid_attributes
        put :update, {:id => casa.to_param, :casa => valid_attributes}, valid_session
        response.should redirect_to(casa)
      end
    end

    describe "with invalid params" do
      it "assigns the casa as @casa" do
        casa = Casa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Casa.any_instance.stub(:save).and_return(false)
        put :update, {:id => casa.to_param, :casa => { "rua" => "invalid value" }}, valid_session
        assigns(:casa).should eq(casa)
      end

      it "re-renders the 'edit' template" do
        casa = Casa.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Casa.any_instance.stub(:save).and_return(false)
        put :update, {:id => casa.to_param, :casa => { "rua" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested casa" do
      casa = Casa.create! valid_attributes
      expect {
        delete :destroy, {:id => casa.to_param}, valid_session
      }.to change(Casa, :count).by(-1)
    end

    it "redirects to the casas list" do
      casa = Casa.create! valid_attributes
      delete :destroy, {:id => casa.to_param}, valid_session
      response.should redirect_to(casas_url)
    end
  end

end
